title: "姿勢の表現方法まとめ"
summary: "自動車、航空機、ドローン、ロボットなどの移動物体の姿勢表現、特に三次元回転を伴ったものについては初学者がとっつきづらい内容である。また、内容によってはいくつかの慣習があり、ネットに散在している情報を適当に集約しただけでは、異なる慣習に基づいたものを混同することにつながり、混乱に陥る。本書では、クォータニオン、回転行列、オイラー角などの三次元回転の表現方法も含めて、一貫性のある姿勢表現の体系をまとめるので、技術者等の一助になればと思う。"
topics: []
published: false
price: 0
toc_depth: 2
chapters:
  - "6b9f8c"
  - "01231b"
  - "d464cd"
  - "a48ce2"
  - "5f0d3e"